language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools

    - build-tools-25.0.2

    # The SDK version used to compile project
    - android-25

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-25